---
- name: Validate website hosting inputs
  ansible.builtin.import_tasks: validate.yml

- name: Prepare website TLS and package state
  ansible.builtin.import_tasks: tls-prep.yml

- name: Enforce development basic authentication
  ansible.builtin.import_tasks: auth.yml

- name: Deploy website content
  ansible.builtin.import_tasks: content.yml

- name: Enforce website certificates
  ansible.builtin.import_tasks: certificates.yml

- name: Enforce nginx website deployment
  ansible.builtin.import_tasks: nginx.yml
