---
- name: Store bastion runner environment
  ansible.builtin.import_tasks: environment.yml

- name: Prepare bastion runner directories
  ansible.builtin.import_tasks: directories.yml

- name: Install bastion runner files
  ansible.builtin.import_tasks: install.yml

- name: Manage bastion runner timers
  ansible.builtin.import_tasks: timers.yml

- name: Remove bastion runner files from non-bastion hosts
  ansible.builtin.import_tasks: remove-non-bastion.yml
