---
- name: Ensure GCS restic bucket exists
  google.cloud.gcp_storage_bucket:
    name: "{{ restic_backup_remote_gcs_bucket_name }}"
    project: "{{ restic_backup_remote_gcs_project_id }}"
    auth_kind: serviceaccount
    service_account_contents: "{{ restic_backup_remote_gcs_credentials_json }}"
    location: "{{ restic_backup_remote_gcs_location }}"
    storage_class: "{{ restic_backup_remote_gcs_storage_class }}"
    labels: "{{ restic_backup_remote_gcs_labels }}"
    versioning:
      enabled: false
    iam_configuration:
      public_access_prevention: enforced
      uniform_bucket_level_access:
        enabled: true
    state: present
  delegate_to: localhost
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  when: restic_backup_remote_gcs_enabled | bool
  no_log: true
