---
automation_notifications_environment: prod
automation_notifications_timezone: America/Chicago
automation_notifications_target: "{{ inventory_hostname }}"

automation_notifications_colors:
  info: 5811424
  success: 4175499
  warning: 13211450
  error: 14042437
