---
baseline_validation_environment: prod
baseline_validation_timezone: America/Chicago
baseline_validation_certificate_environment: staging
baseline_validation_tls_mode: host
baseline_validation_vault_checkout_dir: /home/ansible/grayhaven-vault
