---
- name: Validate nginx configuration
  ansible.builtin.command:
    cmd: nginx -t
  changed_when: false
  listen: Reload nginx

- name: Reload nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: reloaded
  listen: Reload nginx
