---
system_packages_ansible_runtime_venv: /home/ansible/ansible-runner/ansible-runtime

system_packages_bootstrap_runner_packages:
  - git
  - python3-pip

system_packages_admin_packages:
  - bash-completion
  - bind-utils
  - epel-release
  - python3
  - python3-pip
  - setroubleshoot-server
  - tmux
  - vim

system_packages_required_packages:
  - acl
  - audit
  - chrony
  - curl
  - fail2ban
  - firewalld
  - git
  - httpd-tools
  - NetworkManager
  - openssh-server
  - python3-firewall
  - python3-libselinux
  - restic
  - yum-utils

system_packages_unneeded_packages:
  - avahi
  - bluez
  - cups
  - nfs-utils
  - rpcbind
  - samba

system_packages_unneeded_services:
  - avahi-daemon
  - bluetooth
  - cups
  - nfs-server
  - rpcbind
  - smb
