---
- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Restart chronyd
  ansible.builtin.service:
    name: chronyd
    state: restarted

- name: Reload firewalld
  ansible.builtin.raw: |
    nohup firewall-cmd --reload >/dev/null 2>&1 </dev/null &
    echo reloading
  changed_when: "'reloading' in managed_baseline_firewalld_reload.stdout_lines"
  register: managed_baseline_firewalld_reload
  vars:
    ansible_ssh_args: "{{ managed_baseline_firewalld_ssh_args }}"

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: Restart systemd-journald
  ansible.builtin.service:
    name: systemd-journald
    state: restarted
