---
- name: Check current system timezone
  ansible.builtin.command:
    cmd: timedatectl show --property=Timezone --value
  register: time_sync_current_timezone
  changed_when: false

- name: Set system timezone
  ansible.builtin.command:
    cmd: "timedatectl set-timezone {{ grayhaven_timezone }}"
  changed_when: true
  when: time_sync_current_timezone.stdout != grayhaven_timezone

- name: Configure chrony
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart chronyd

- name: Enable and start chronyd
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: true
